version: "3.1"
volumes:
  mongo_data:
services:
  sms-api:
    build: .
    # context: .
    # dockerfile: Dockerfile
    # These variables are passed to Dockerfile.
    # args:
    #   - HOST_UID=${HOST_UID:-4000}
    #   - HOST_USER=${HOST_USER:-nodummy}
    restart: unless-stopped
    container_name: sms-management-api
    image: api:latest
    links:
      - mongo
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - ${PWD:-.}:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
    command: yarn start:node
    tty: true
    stdin_open: true
  mongo:
    restart: unless-stopped
    image: mongo:3.6.4
    volumes:
      - ${PWD}/data/db:/data/db
    ports:
      - 27017:27017
