default: &default
  docker:
    - image: circleci/node:11.4.0
  working_directory: ~/repo
restore_cache: &restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
install_dependencies: &install_dependencies
  run:
    name: install dependencies
    command: yarn install
save_cache: &save_cache
  save_cache:
    key: dependency-cache-{{ checksum "package.json"}}
    paths:
      - ./node_modules

version: 2
jobs:
  tests:
    <<: *default
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: run tests
          command: yarn run test
      - run:
          name: upload coveralls
          command: yarn run test:coverage

workflows:
  version: 2
  build_test:
    jobs:
      - tests
